export const ROLES = {
  EDUCADOR: 'EDUCADOR',
  FAMILIA: 'FAMILIA',
  JOVEN: 'JOVEN'
};

export const FUNCIONES = {
  LOBATOS: 'LOBATOS',
  SCOUTS: 'SCOUTS',
  CAMINANTES: 'CAMINANTES',
  ROVERS: 'ROVERS',
  JEFE_GRUPO: 'JEFE_GRUPO', // Admin total
  ASISTENTE_PROG: 'ASISTENTE_PROG', // Ve todas las ramas
  ASISTENTE_ADM: 'ASISTENTE_ADM', // Finanzas y nóminas
  ASISTENTE_ADULTOS: 'ASISTENTE_ADULTOS', // Gestión de educadores
  ASISTENTE_COM: 'ASISTENTE_COM', // Gestión de web/noticias
  
  // Funciones de Jóvenes
  PROTAGONISTA_LOBATO: 'PROTAGONISTA_LOBATO',
  PROTAGONISTA_SCOUT: 'PROTAGONISTA_SCOUT',
  PROTAGONISTA_CAMINANTE: 'PROTAGONISTA_CAMINANTE',
  PROTAGONISTA_ROVER: 'PROTAGONISTA_ROVER'
};